-- Generated by wallust — do not edit (edit the template instead)
return {
    bg      = "#101017",
    fg      = "#FEFAD7",
    accent  = "#F2E3EF",
    accent2 = "#FCF18E",
    muted   = "#383940",
}
