<?xml version="1.0"?>
<package format="3">
  <name>robot_arm_description</name>
  <version>0.1.0</version>
  <description>Starter 6-DOF robot arm description</description>
  <maintainer email="santapongsondhi@gmail.com">santapong</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher_gui</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>xacro</exec_depend>
</package>
