[package]
name = "hypr-appdock"
version = "0.1.0"
edition = "2021"

[dependencies]
hyprdesk = { path = "../hyprdesk", features = ["draw"] }
smithay-client-toolkit = "0.19.2"
wayland-client = "0.31"
calloop = "0.14"
calloop-wayland-source = "0.4"
tiny-skia = "0.11"
serde_json = "1"
signal-hook = "0.3"
libc = "0.2"
