# Managed by wallpaper.sh — run 'wallpaper.sh <image|folder> [monitor]' to change.
wallpaper {
    monitor  = 
    path     = /home/santapong/Pictures/wallpaper/Cartethyia.jpg
    fit_mode = cover
}
wallpaper {
    monitor  = DP-1
    path     = /home/santapong/Pictures/wallpaper/1358521.png
    fit_mode = cover
}
wallpaper {
    monitor  = HDMI-A-2
    path     = /home/santapong/Pictures/wallpaper/v2osk-1Z2niiBPg5A-unsplash.jpg
    fit_mode = cover
}
wallpaper {
    monitor  = HDMI-A-1
    path     = /home/santapong/Pictures/10072025/hsinv2.jpg
    fit_mode = cover
}
splash = false
ipc = true
