-- Generated by wallust — do not edit (edit the template instead)
return {
    bg      = "{{background}}",
    fg      = "{{foreground}}",
    accent  = "{{color12}}",
    accent2 = "{{color14}}",
    muted   = "{{color0}}",
}
